#pragma kernel CalculateGridArgsKernel

RWStructuredBuffer<uint> _IndirectArgsBuffer;
uint _MaxParticleCount;

[numthreads(1, 1, 1)]
void CalculateGridArgsKernel(uint3 id : SV_DispatchThreadID)
{
    uint rawCount = min(_IndirectArgsBuffer[3], _MaxParticleCount);
    _IndirectArgsBuffer[3] = rawCount;
    uint threadGroupsX = (rawCount + 63u) / 64u;
    _IndirectArgsBuffer[0] = threadGroupsX;
    _IndirectArgsBuffer[1] = 1;
    _IndirectArgsBuffer[2] = 1;
}
